from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

try:
    __version__ = _pkg_version("py-agent-ctrl")
except PackageNotFoundError:
    __version__ = "0.0.0"

from py_agent_ctrl.api.events import (
    AgentEvent,
    AgentFileChangeEvent,
    AgentPlanUpdateEvent,
    AgentReasoningEvent,
    AgentResultEvent,
    AgentTextEvent,
    AgentToolCallEvent,
    AgentUnknownEvent,
    AgentUsageEvent,
    AgentWarningEvent,
    StreamResult,
)
from py_agent_ctrl.api.facade import AgentCtrl
from py_agent_ctrl.api.models import (
    AgentRequest,
    AgentResponse,
    AgentType,
    BridgeCapabilities,
    ClaudeCodeProviderOptions,
    ClaudePermissionMode,
    CodexProviderOptions,
    CodexSandboxMode,
    GeminiApprovalMode,
    GeminiProviderOptions,
    PermissionOption,
    PermissionOptionKind,
    PermissionOutcome,
    PermissionRequest,
    PermissionResponse,
    SandboxDriver,
    SessionCapabilities,
    SessionInfo,
    SessionOperation,
    TokenUsage,
    ToolCall,
)
from py_agent_ctrl.services.core.errors import (
    AgentError,
    AgentExecutionError,
    BinaryNotFoundError,
    JsonDecodeFailureError,
    ProcessFailedError,
    ProcessStartError,
    ProcessTimeoutError,
    ProviderParseFailureError,
    UnsupportedSessionOperationError,
    WorkingDirectoryNotFoundError,
)

__all__ = [
    "AgentCtrl",
    "AgentError",
    "AgentEvent",
    "AgentFileChangeEvent",
    "AgentPlanUpdateEvent",
    "AgentRequest",
    "AgentResponse",
    "AgentReasoningEvent",
    "AgentResultEvent",
    "AgentTextEvent",
    "AgentToolCallEvent",
    "AgentType",
    "AgentUnknownEvent",
    "AgentUsageEvent",
    "AgentWarningEvent",
    "BinaryNotFoundError",
    "BridgeCapabilities",
    "ClaudeCodeProviderOptions",
    "ClaudePermissionMode",
    "CodexProviderOptions",
    "CodexSandboxMode",
    "AgentExecutionError",
    "GeminiApprovalMode",
    "GeminiProviderOptions",
    "JsonDecodeFailureError",
    "PermissionOption",
    "PermissionOptionKind",
    "PermissionOutcome",
    "PermissionRequest",
    "PermissionResponse",
    "ProcessFailedError",
    "ProcessStartError",
    "ProcessTimeoutError",
    "ProviderParseFailureError",
    "SandboxDriver",
    "SessionCapabilities",
    "SessionInfo",
    "SessionOperation",
    "StreamResult",
    "TokenUsage",
    "ToolCall",
    "UnsupportedSessionOperationError",
    "WorkingDirectoryNotFoundError",
]
